export { default as LandingPage } from "./landingPage/LandingPage";
export { default as LoginPage } from "./loginPage/LoginPage";
export { default as RegisterPage } from "./registerPage/Register";
export { default as ForgotPasswordPage } from "./forgotPassword/ForgotPassword";
export { default as ResetPasswordPage } from "./resetPassword/ResetPassword";
export { default as VerifyEmailPage } from "./verifyEmail/VerifyEmail";
export { default as HomePage } from "./home/Home";
export { default as DashboardPage } from "./dashboard/Dashboard";
export { default as NotfoundPage } from "./notFound/NotFound";
